from pathlib import Path
import json
import re

from datasets import load_dataset


# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

DATASET = "wikimedia/wikipedia"
CONFIG = "20231101.es"

OUTPUT_DIR = Path(__file__).parent
ARTICLES_DIR = OUTPUT_DIR / "articles"
METADATA_FILE = OUTPUT_DIR / "metadata.jsonl"

TARGET_CHARS = 1_200_000
MAX_CHARS_PER_TOPIC = 100_000
MIN_ARTICLE_CHARS = 2_000
MAX_ARTICLE_CHARS = 20_000

TOPICS = {
    "astronomia": [
        "astronomía", "astronomo", "astrónomo",
        "estrella", "planeta", "galaxia",
        "universo", "cosmología", "cosmologia",
        "satélite", "satélite natural",
    ],
    "fisica": [
        "física", "fisica", "mecánica", "mecanica",
        "relatividad", "cuántica", "cuantica",
        "partícula", "particula", "energía", "energia",
    ],
    "geologia": [
        "geología", "geologia", "mineral", "roca",
        "tectónica", "tectonica", "volcán", "volcan",
        "paleontología", "paleontologia",
    ],
    "biologia": [
        "biología", "biologia", "organismo", "especie",
        "evolución", "evolucion", "genética", "genetica",
        "animal", "planta", "ecología", "ecologia",
    ],
    "quimica": [
        "química", "quimica", "molécula", "molecula",
        "átomo", "atomo", "elemento químico",
        "reacción química",
    ],
    "matematicas": [
        "matemáticas", "matematicas", "álgebra", "algebra",
        "geometría", "geometria", "teorema",
        "cálculo", "calculo", "número primo",
    ],
    "arqueologia": [
        "arqueología", "arqueologia", "arqueológico",
        "arqueologico", "excavación", "excavacion",
        "yacimiento", "artefacto", "civilización",
        "civilizacion",
    ],
    "historia": [
        "historia", "histórico", "historico",
        "imperio", "reino", "guerra", "revolución",
        "revolucion", "edad media", "antigüedad",
    ],
    "linguistica": [
        "lingüística", "linguistica", "lengua",
        "idioma", "gramática", "gramatica",
        "fonética", "fonetica", "etimología", "etimologia",
    ],
    "geografia": [
        "geografía", "geografia", "continente",
        "océano", "oceano", "río", "rio",
        "montaña", "montana", "desierto",
    ],
    "informatica": [
        "informática", "informatica", "algoritmo",
        "programación", "programacion", "software",
        "hardware", "computación", "computacion",
    ],
    "tecnologia": [
        "tecnología", "tecnologia", "ingeniería",
        "ingenieria", "máquina", "maquina",
        "electrónica", "electronica", "robot",
    ],
}


# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

def clean_text(text):
    """Basic cleanup without rewriting the original article."""
    text = text.replace("\r\n", "\n")
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()


def find_topics(title, text):
    """
    Assign possible topics using the title and the first
    part of the article.

    This is deliberately a simple heuristic.
    """

    sample = f"{title}\n{text[:5000]}".lower()

    matches = []

    for topic, keywords in TOPICS.items():
        score = sum(
            sample.count(keyword.lower())
            for keyword in keywords
        )

        if score > 0:
            matches.append((score, topic))

    matches.sort(reverse=True)

    return [topic for _, topic in matches]


def safe_filename(article_id, title):
    """Create a filesystem-safe filename."""

    title = re.sub(
        r"[^\w\- ]+",
        "",
        title,
        flags=re.UNICODE,
    )

    title = re.sub(
        r"\s+",
        "_",
        title.strip(),
    )

    title = title[:80]

    return f"{article_id}_{title}.txt"


def clear_previous_output():
    """
    Remove only the files generated by this script.

    The Hugging Face cache is NOT touched.
    """

    if ARTICLES_DIR.exists():
        for path in ARTICLES_DIR.glob("*.txt"):
            path.unlink()

    if METADATA_FILE.exists():
        METADATA_FILE.unlink()


# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

def main():

    ARTICLES_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Clean the partial output from previous attempts.
    clear_previous_output()

    dataset = load_dataset(
        DATASET,
        CONFIG,
        split="train",
        streaming=True,
    )

    topic_chars = {
        topic: 0
        for topic in TOPICS
    }

    total_chars = 0
    articles_saved = 0

    with METADATA_FILE.open(
        "w",
        encoding="utf-8",
    ) as metadata:

        for article in dataset:

            if total_chars >= TARGET_CHARS:
                break

            article_id = article["id"]
            title = article["title"]
            text = clean_text(article["text"])

            # Ignore very small articles.
            if len(text) < MIN_ARTICLE_CHARS:
                continue

            # Ignore huge articles.
            if len(text) > MAX_ARTICLE_CHARS:
                continue

            topics = find_topics(
                title,
                text,
            )

            if not topics:
                continue

            # Choose the matching topic with the least
            # amount of data collected so far.
            available_topics = [
                topic
                for topic in topics
                if topic_chars[topic]
                < MAX_CHARS_PER_TOPIC
            ]

            if not available_topics:
                continue

            topic = min(
                available_topics,
                key=lambda t: topic_chars[t],
            )

            remaining_topic = (
                MAX_CHARS_PER_TOPIC
                - topic_chars[topic]
            )

            remaining_total = (
                TARGET_CHARS
                - total_chars
            )

            max_chars = min(
                remaining_topic,
                remaining_total,
            )

            if len(text) > max_chars:
                continue

            filename = safe_filename(
                article_id,
                title,
            )

            output_path = (
                ARTICLES_DIR / filename
            )

            output_path.write_text(
                text + "\n",
                encoding="utf-8",
            )

            metadata.write(
                json.dumps(
                    {
                        "id": article_id,
                        "title": title,
                        "topic": topic,
                        "chars": len(text),
                        "url": article["url"],
                        "source": DATASET,
                        "config": CONFIG,
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )

            topic_chars[topic] += len(text)
            total_chars += len(text)
            articles_saved += 1

            if articles_saved % 25 == 0:
                print(
                    f"Articles: {articles_saved:4d} | "
                    f"chars: {total_chars:8,d} | "
                    f"topic: {topic}"
                )

    print()
    print("=" * 60)
    print("Wikipedia extraction complete")
    print("=" * 60)
    print(f"Articles: {articles_saved}")
    print(f"Characters: {total_chars:,}")
    print()

    for topic, chars in topic_chars.items():
        print(
            f"{topic:15s} {chars:8,d}"
        )

    print()
    print(
        f"Articles directory: {ARTICLES_DIR}"
    )
    print(
        f"Metadata:           {METADATA_FILE}"
    )


if __name__ == "__main__":
    main()
